export const images = [
    import('../assets/photos/Angel frame.jpg'),
    import('../assets/photos/Angels of Oradea.jpg'),
    import('../assets/photos/Artist on street v1.jpg'),
    import('../assets/photos/Artist on street v2.jpg'),
    import('../assets/photos/Busy winter in Zurich.jpg'),
    import('../assets/photos/Croix domini.jpg'),
    import('../assets/photos/Cubanito Fat Bob.jpg'),
    import('../assets/photos/Fisherman preparing.jpg'),
    import('../assets/photos/Fisherman sillhouette.jpg'),
    import('../assets/photos/Fishing village.jpg'),
    import('../assets/photos/Gulf of Poets.jpg'),
    import('../assets/photos/Halong Bay Rock.jpg'),
    import('../assets/photos/Kid over sunset.jpg'),
    import('../assets/photos/Lonely boat.jpg'),
    import('../assets/photos/Lonely stork.jpg'),
    import('../assets/photos/One legged bird.jpg'),
    import('../assets/photos/Palm tree sunset.jpg'),
    import('../assets/photos/Palm tree sunset2.jpg'),
    import('../assets/photos/Passing life.jpg'),
    import('../assets/photos/Stelvio pass v2.jpg'),
    import('../assets/photos/Stelvio pass.jpg'),
    import('../assets/photos/Stork over houses.jpg'),
    import('../assets/photos/Story family.jpg'),
    import('../assets/photos/Sunset between trees.jpg'),
];

export const imageDescriptions = [
    { title: 'Angel frame', description: 'An artistic angelic frame.' },
    { title: 'Angels of Oradea', description: 'Angelic figures in Oradea.' },
    { title: 'Artist on street v1', description: 'Street artist creating art.' },
    { title: 'Artist on street v2', description: 'Another street artist at work.' },
    { title: 'Busy winter in Zurich', description: `'Zurich's bustling winter scene.'` },
    { title: 'Croix domini', description: 'A peaceful cross in nature.' },
    { title: 'Cubanito Fat Bob', description: 'Cubanito Fat Bob motorcycle.' },
    { title: 'Fisherman preparing', description: 'A fisherman getting ready.' },
    { title: 'Fisherman sillhouette', description: 'Silhouetted fisherman.' },
    { title: 'Fishing village', description: 'Charming fishing village.' },
    { title: 'Gulf of Poets', description: 'Scenic Gulf of Poets.' },
    { title: 'Halong Bay Rock', description: 'Iconic rock formations in Halong Bay.' },
    { title: 'Kid over sunset', description: 'A kid enjoying the sunset.' },
    { title: 'Lonely boat', description: 'A solitary boat on the water.' },
    { title: 'Lonely stork', description: 'A lone stork in the wild.' },
    { title: 'One legged bird', description: 'A one-legged bird in nature.' },
    { title: 'Palm tree sunset', description: 'Palm trees during a stunning sunset.' },
    { title: 'Palm tree sunset2', description: 'Another beautiful palm tree sunset.' },
    { title: 'Passing life', description: 'Capturing the passage of life.' },
    { title: 'Stelvio pass v2', description: 'Stunning Stelvio mountain pass.' },
    { title: 'Stelvio pass', description: 'Scenic drive on the Stelvio pass.' },
    { title: 'Stork over houses', description: 'A stork flying over houses.' },
    { title: 'Story family', description: `'A family's heartwarming story.'` },
    { title: 'Sunset between trees', description: 'A tranquil sunset scene.' },
];